# Generated by Django 5.2.3 on 2026-07-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("search", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactLead",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=80, verbose_name="Name")),
                ("organization", models.CharField(blank=True, max_length=120, verbose_name="Organization")),
                ("contact", models.CharField(max_length=120, verbose_name="Contact")),
                (
                    "interest",
                    models.CharField(
                        choices=[
                            ("agent", "EEG model agent"),
                            ("training", "Robot training"),
                            ("companion", "Robot companion"),
                            ("general", "General inquiry"),
                        ],
                        default="general",
                        max_length=32,
                        verbose_name="Interest",
                    ),
                ),
                ("message", models.TextField(verbose_name="Message")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created at")),
            ],
            options={
                "verbose_name": "Contact lead",
                "verbose_name_plural": "Contact leads",
                "ordering": ["-created_at"],
            },
        ),
    ]

